channels:
  - conda-forge

dependencies:
  # Basics -----------------
  - python=3.10
  - pip

  # Key dependencies -------
  - ipywidgets=8.1
  - ipytree=0.2
  - python-jsonpath
  - jupyter
  - nest-simulator=3.8
  - numba=0.60
  - numpy=1.23
  - matplotlib=3.7
  - openpyxl=3.1
  - pandas=1.5
  - pydantic=2.7
  - pyqtgraph
  - pyyaml=6.0
  - requests=2.31
  - scipy=1.9
  - sqlalchemy
  - traitlets=5.1
  - tqdm=4.66

  - pip:
      - anndata
      - allensdk
      - bmtk
      - mpi4py
      - parse
      - pytree
      - git+https://github.com/alleninstitute/abc_atlas_access
      - git+https://github.com/alleninstitute/neuroanalysis
      - git+https://github.com/alleninstitute/aisynphys
