channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  # Requirements for airavata cerebrum
  - anndata
  - anywidget
  - boto3
  - duckdb
  - fastexcel
  - h5py
  - ipywidgets
  - jupyter
  - lmfit
  - marimo
  - matplotlib
  - nodejs
  - numba
  - numpy
  - pandas
  - pillow
  - polars
  - psutil
  - pydantic
  - pyqt
  - python-jsonpath
  - pyyaml
  - seaborn
  - scikit-image
  - scikit-learn
  - scipy
  - sqlalchemy
  - statsmodels
  - tqdm
  - traitlets
  # PIP dependencies
  - pip:
      - allensdk
      - awitree
      - neuroanalysis
      - psycopg2-binary
      - pyqtgraph
      - typing-extensions
