channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  # Requirements for airavata cerebrum
  - jupyter
  - leidenalg
  - nest-simulator
  - marimo
  - mpi4py
  - openmpi-mpicc
  - pyarrow
  - python-dateutil
  - python-igraph

  # PIP dependencies
  - pip:
      - airavata-cerebrum
      - bmtk
      - parse
      - psutil
      - sonata
      - sqlglot
      - quak
